Repository UpendoVentures/OpenContentTemplates-Razor, pull requests merged in 2025-04, with the labels that each got.

#16 Features/porto paragraphs
  Porto-Paragraphs/Template-data.json
  Porto-Paragraphs/Template.cshtml
  Porto-Paragraphs/builder.json
  Porto-Paragraphs/data.json
  Porto-Paragraphs/options.json
  Porto-Paragraphs/schema.json
  Porto-Paragraphs/template-options.json
  Porto-Paragraphs/template-schema.json
Labels: enhancement

#17 Fixed builder field type & default message
  Porto-Paragraphs/builder.json
  Porto-Paragraphs/data.json
  Porto-Paragraphs/options.json
Labels: bug

#18 Rendering the ck editor
  Porto-Paragraphs/builder.json
  Porto-Paragraphs/options.json
Labels: bug

#20 Resolves #19
  Porto-Image/Template-data.json
  Porto-Image/Template.cshtml
  Porto-Image/builder.json
  Porto-Image/data.json
  Porto-Image/options.json
  Porto-Image/schema.json
  Porto-Image/template-options.json
  Porto-Image/template-schema.json
  Porto-Image/view.json
Labels: enhancement

#21 Adds missing update from previous missing updates
  Porto-Paragraphs/Template.cshtml
Labels: bug

#25 Features/porto paragraphs side image template
  Porto-Image/Template.cshtml
  Porto-Paragraphs-Side-Image/Template-data.json
  Porto-Paragraphs-Side-Image/Template.cshtml
  Porto-Paragraphs-Side-Image/builder.json
  Porto-Paragraphs-Side-Image/data.json
  Porto-Paragraphs-Side-Image/options.json
  Porto-Paragraphs-Side-Image/schema.json
  Porto-Paragraphs-Side-Image/template-options.json
  Porto-Paragraphs-Side-Image/template-schema.json
  Porto-Paragraphs-Side-Image/view.json
Labels: bug, enhancement

#24 OpenContentTemplates-Razor Documentation
  Porto-Image/Porto-Image.html
  Porto-Image/images/template-settings.png
  Porto-Image/images/usage-example.png
  Porto-Image/images/view-example.png
  Porto-Paragraphs/Porto-Paragraphs.html
  Porto-Paragraphs/builder.json
  Porto-Paragraphs/images/template-settings.png
  Porto-Paragraphs/images/usage-example.png
  Porto-Paragraphs/images/view-example.png
  Porto-Paragraphs/options.json
  Porto-Paragraphs/schema.json
  Porto-Paragraphs/view.json
Labels: bug, documentation, enhancement

#26 Resolved display issue
  Porto-Paragraphs-Side-Image/Template.cshtml
Labels: bug

#27 Bugs/resolved settings rendering
  Porto-Image/Template-data.json
  Porto-Image/Template.cshtml
  Porto-Paragraphs-Side-Image/Template-data.json
  Porto-Paragraphs-Side-Image/Template.cshtml
  Porto-Paragraphs/Template-data.json
  Porto-Paragraphs/Template.cshtml
Labels: bug, enhancement

#28 Button template updates
  Porto-Buttons/Porto-Buttons.html
  Porto-Buttons/Template-builder.json
  Porto-Buttons/Template-data.json
  Porto-Buttons/Template-view.json
  Porto-Buttons/Template.cshtml
  Porto-Buttons/builder.json
  Porto-Buttons/image/edit.png
  Porto-Buttons/image/edit0.png
  Porto-Buttons/image/edit1.png
  Porto-Buttons/image/template settings.png
  Porto-Buttons/image/template settings0.png
  Porto-Buttons/image/template settings1.png
  Porto-Buttons/image/template settings2.png
  Porto-Buttons/image/template settings3.png
  Porto-Buttons/options.json
  Porto-Buttons/schema.json
  Porto-Buttons/template-options.json
  Porto-Buttons/template-schema.json
  Porto-Buttons/view.json
Labels: documentation, enhancement

#29 Update Porto-Tabs Template
  Porto-Tabs/Porto-Tabs.html
  Porto-Tabs/Template-view.json
  Porto-Tabs/Template.cshtml
  Porto-Tabs/builder.json
  Porto-Tabs/data.json
  Porto-Tabs/image/edit.png
  Porto-Tabs/options.json
  Porto-Tabs/schema.json
  Porto-Tabs/template-builder.json
  Porto-Tabs/template-options.json
  Porto-Tabs/template-schema.json
  Porto-Tabs/view.json
Labels: documentation, enhancement

#30 Typo in some template's top margin settings
  Porto-Image/template-schema.json
  Porto-Paragraphs-Side-Image/template-schema.json
  Porto-Paragraphs/template-schema.json
Labels: bug

#31 Update Porto-Tabs
  Porto-Tabs/builder.json
  Porto-Tabs/options.json
  Porto-Tabs/schema.json
Labels: bug, documentation

#33 Adds top & bottom settings for margins & padding
  Porto-Call-To-Action/Template-data.json
  Porto-Call-To-Action/Template.cshtml
  Porto-Call-To-Action/builder.json
  Porto-Call-To-Action/options.json
  Porto-Call-To-Action/template-options.json
  Porto-Call-To-Action/template-schema.json
Labels: enhancement

#34 Adds a link target option to CTA
  Porto-Call-To-Action/Template.cshtml
  Porto-Call-To-Action/builder.json
  Porto-Call-To-Action/options.json
  Porto-Call-To-Action/schema.json
  Porto-Call-To-Action/view.json
Labels: enhancement

#37 Features/paragraph side image updates
  Porto-Paragraphs-Side-Image/Template-data.json
  Porto-Paragraphs-Side-Image/Template.cshtml
  Porto-Paragraphs-Side-Image/builder.json
  Porto-Paragraphs-Side-Image/options.json
  Porto-Paragraphs-Side-Image/template-options.json
  Porto-Paragraphs-Side-Image/template-schema.json
Labels: enhancement

#36 Update Porto-Icon-Boxes
  Porto-Icon-Boxes/Porto-Icon-Boxes.html
  Porto-Icon-Boxes/Template.cshtml
Labels: bug, documentation, enhancement

#39 Create Porto-ExtensionList
  Porto-ExtensionList/Template.cshtml
  Porto-ExtensionList/builder.json
  Porto-ExtensionList/data.json
  Porto-ExtensionList/options.json
  Porto-ExtensionList/schema.json
  Porto-ExtensionList/template-options.json
  Porto-ExtensionList/template-schema.json
  Porto-ExtensionList/view.json
Labels: enhancement

#41 Update Template.cshtml
  Porto-ExtensionList/Template.cshtml
Labels: bug, enhancement

#44 Porto-Buttons template link to use URL type
  Porto-Buttons/Template.cshtml
  Porto-Buttons/builder.json
  Porto-Buttons/options.json
Labels: enhancement

#46 Update Porto-ExtensionList Template.cshtml
  Porto-ExtensionList/Template.cshtml
Labels: bug, enhancement

#43 Disable DNN Admin Messages in All Razor Templates
  DNN-Messages/Template.cshtml
  Header-Banner-NoBS/Template.cshtml
  Modal-Dialog-NoBS/Template.cshtml
  Modal-Dialog/Template.cshtml
  Move-Plugin/Template.cshtml
  Porto-Accordion/Template.cshtml
  Porto-Alerts/Template.cshtml
  Porto-Animations/Template.cshtml
  Porto-Arrows/Template.cshtml
  Porto-Before-After/Template.cshtml
  Porto-Blockquotes/Template.cshtml
  Porto-Buttons/Template.cshtml
  Porto-Call-To-Action/Template.cshtml
  Porto-Carousel/Template.cshtml
  Porto-Countdowns/Template.cshtml
  Porto-Counters/Template.cshtml
  Porto-Dividers/Template.cshtml
  Porto-ExtensionList/Template.cshtml
  Porto-Forms/Template.cshtml
  Porto-Headings/Template.cshtml
  Porto-Icon-Boxes/Template.cshtml
  Porto-Icons/Template.cshtml
  Porto-Image-Frames/Template.cshtml
  Porto-Image-Gallery/Template.cshtml
  Porto-Image/Template.cshtml
  Porto-Labels-Headings/Template.cshtml
  Porto-Labels/Template.cshtml
  Porto-Lightboxes-Dialog/Template.cshtml
  Porto-Lightboxes/Template.cshtml
  Porto-Maps-Template/Template.cshtml
  Porto-Medias/Template.cshtml
  Porto-Modals-Forms/Template.cshtml
  Porto-Modals/Template.cshtml
  Porto-Ordered-List/Template.cshtml
  Porto-Pagination/Template.cshtml
  Porto-Paragraphs-Side-Image/Template.cshtml
  Porto-Paragraphs/Template.cshtml
  Porto-Popover/Template.cshtml
  Porto-Posts/Template.cshtml
  Porto-Pricing-Tables/Template.cshtml
  Porto-Progress-Bar-Circular/Template.cshtml
  Porto-Progress-Bar/Template.cshtml
  Porto-Section-Parallax/Template.cshtml
  Porto-Shapes-Dividers/Template.cshtml
  Porto-Social-Media-Icons/Template.cshtml
  Porto-Sticky-Elements/Template.cshtml
  Porto-Tables/Template.cshtml
  Porto-Tabs/Template.cshtml
  Porto-Testimonials-Carousel/Template.cshtml
  Porto-Testimonials/Template.cshtml
  Porto-Toggle/Template.cshtml
  Porto-Tooltip/Template.cshtml
  Porto-TypeWriter/Template.cshtml
  Porto-Typography/Template.cshtml
  Porto-UnOrdered-List/Template.cshtml
  Porto-Word-Rotator/Template.cshtml
Labels: enhancement

#48 Update Porto-ExtensionList
  Porto-ExtensionList/Template.cshtml
  Porto-ExtensionList/builder.json
  Porto-ExtensionList/options.json
  Porto-ExtensionList/template-options.json
  Porto-ExtensionList/template-schema.json
  Porto-ExtensionList/view.json
Labels: bug, enhancement

#49 Added template settings for margins/padding & BS wrapper
  Porto-Countdowns/Template-data.json
  Porto-Countdowns/Template.cshtml
  Porto-Countdowns/template-options.json
  Porto-Countdowns/template-schema.json
Labels: enhancement

#50 Added a new Porto-Content-Cards template
  Porto-Content-Cards/Template-data.json
  Porto-Content-Cards/Template.cshtml
  Porto-Content-Cards/builder.json
  Porto-Content-Cards/data.json
  Porto-Content-Cards/options.json
  Porto-Content-Cards/schema.json
  Porto-Content-Cards/template-options.json
  Porto-Content-Cards/template-schema.json
  Porto-Content-Cards/view.json
Labels: enhancement

#52 Adds BS5 markup to ensure the image is center aligned in the container
  Porto-Image/Template.cshtml
Labels: enhancement

#53 Adds a new template to easily highlight 6 benefits of something
  Porto-Six-Benefits-Grid/Porto-Paragraphs.html
  Porto-Six-Benefits-Grid/Template-data.json
  Porto-Six-Benefits-Grid/Template.cshtml
  Porto-Six-Benefits-Grid/builder.json
  Porto-Six-Benefits-Grid/data.json
  Porto-Six-Benefits-Grid/options.json
  Porto-Six-Benefits-Grid/schema.json
  Porto-Six-Benefits-Grid/template-options.json
  Porto-Six-Benefits-Grid/template-schema.json
  Porto-Six-Benefits-Grid/view.json
Labels: enhancement

#54 Enh/porto extensionslist template improvements
  Porto-ExtensionList/Template.cshtml
  Porto-ExtensionList/builder.json
  Porto-ExtensionList/options.json
  Porto-ExtensionList/schema.json
Labels: enhancement

#55 Prevents design issues from nested DOM in the WYSIWYG output
  Porto-ExtensionList/Template.cshtml
Labels: bug

#56 Disappear on scroll, proper JS/CSS include, placeholder to find it
  Header-Banner-NoBS/Template.cshtml
  Header-Banner-NoBS/banner-scripts.js
  Header-Banner-NoBS/banner-styles.css
Labels: bug, enhancement

#60 Features/minor updates
  Porto-ExtensionList/Template.cshtml
  Porto-Paragraphs-Side-Image/Template.cshtml
Labels: bug, enhancement
